/**
 * The most each published bet mode can actually pay, as a multiple of the bet.
 *
 * GENERATED - do not edit by hand. Written by scripts/mode-ceilings.js from
 * math-sdk/games/ride_the_bus/library/stats_summary.json, which run.py runs at
 * the end of every math build. Regenerate after a rebuild; these move with the
 * simulation set.
 *
 * Committed rather than read at runtime because the math library is gitignored
 * in its entirety - the 1.6 GB of published books never enters the repo, so
 * a checkout has nothing to read. modeCeilings.test.ts cross-checks this file
 * against the build when one is present, and skips when it is not.
 *
 * WHY THIS IS NOT ENUMERATED IN THE CLIENT. The four guesses fix a combination,
 * and its theoretical ceiling is derivable from payout.ts. But the RGS can only
 * pay what its lookup table holds, and the published tables are sampled: for a
 * fixed colour + higher/lower + inside/outside, heart and diamond must share a
 * theoretical ceiling and half the time they do not. An enumeration would
 * therefore print a figure ABOVE what the mode can pay, on roughly half the
 * modes - which is the overstatement this table exists to correct.
 *
 * NOT the same number as FAMILY_RULES[f].maxWin, and both are wanted. That one
 * is the most the FAMILY can reach - the headline, true of the mode a player is
 * choosing between. This one is the most THIS BET can reach. Only 8 of the 64
 * combinations in each family reach their family's figure; the median Classic
 * mode stops at 268.8x against a stated 1354.2x.
 */

/** Mode name (as published, family prefix and all) to its ceiling in bet multiples. */
export const MODE_CEILINGS: Readonly<Record<string, number>> = Object.freeze({
  'red_higher_inside_heart': 290.9,
  'red_higher_inside_diamond': 268.8,
  'red_higher_inside_club': 268.8,
  'red_higher_inside_spade': 268.8,
  'red_higher_outside_heart': 68.2,
  'red_higher_outside_diamond': 74.4,
  'red_higher_outside_club': 68.2,
  'red_higher_outside_spade': 68.2,
  'red_higher_equal_heart': 381.9,
  'red_higher_equal_diamond': 381.9,
  'red_higher_equal_club': 352.9,
  'red_higher_equal_spade': 381.9,
  'red_lower_inside_heart': 317.4,
  'red_lower_inside_diamond': 290.9,
  'red_lower_inside_club': 250.1,
  'red_lower_inside_spade': 268.8,
  'red_lower_outside_heart': 74.4,
  'red_lower_outside_diamond': 74.4,
  'red_lower_outside_club': 68.2,
  'red_lower_outside_spade': 68.2,
  'red_lower_equal_heart': 381.9,
  'red_lower_equal_diamond': 381.9,
  'red_lower_equal_club': 352.9,
  'red_lower_equal_spade': 381.9,
  'red_equal_outside_heart': 84.8,
  'red_equal_outside_diamond': 84.8,
  'red_equal_outside_club': 84.8,
  'red_equal_outside_spade': 84.8,
  'red_equal_equal_heart': 1354.2,
  'red_equal_equal_diamond': 1354.2,
  'red_equal_equal_club': 1354.2,
  'red_equal_equal_spade': 1354.2,
  'black_higher_inside_heart': 290.9,
  'black_higher_inside_diamond': 268.8,
  'black_higher_inside_club': 290.9,
  'black_higher_inside_spade': 317.4,
  'black_higher_outside_heart': 68.2,
  'black_higher_outside_diamond': 68.2,
  'black_higher_outside_club': 74.4,
  'black_higher_outside_spade': 74.4,
  'black_higher_equal_heart': 381.9,
  'black_higher_equal_diamond': 352.9,
  'black_higher_equal_club': 381.9,
  'black_higher_equal_spade': 381.9,
  'black_lower_inside_heart': 268.8,
  'black_lower_inside_diamond': 268.8,
  'black_lower_inside_club': 268.8,
  'black_lower_inside_spade': 317.4,
  'black_lower_outside_heart': 68.2,
  'black_lower_outside_diamond': 68.2,
  'black_lower_outside_club': 74.4,
  'black_lower_outside_spade': 74.4,
  'black_lower_equal_heart': 381.9,
  'black_lower_equal_diamond': 381.9,
  'black_lower_equal_club': 381.9,
  'black_lower_equal_spade': 381.9,
  'black_equal_outside_heart': 84.8,
  'black_equal_outside_diamond': 84.8,
  'black_equal_outside_club': 84.8,
  'black_equal_outside_spade': 84.8,
  'black_equal_equal_heart': 1354.2,
  'black_equal_equal_diamond': 1354.2,
  'black_equal_equal_club': 1354.2,
  'black_equal_equal_spade': 1354.2,
  'sc_red_higher_inside_heart': 133.6,
  'sc_red_higher_inside_diamond': 124.5,
  'sc_red_higher_inside_club': 124.5,
  'sc_red_higher_inside_spade': 124.5,
  'sc_red_higher_outside_heart': 39.5,
  'sc_red_higher_outside_diamond': 42.7,
  'sc_red_higher_outside_club': 39.5,
  'sc_red_higher_outside_spade': 39.5,
  'sc_red_higher_equal_heart': 172.2,
  'sc_red_higher_equal_diamond': 172.2,
  'sc_red_higher_equal_club': 160.5,
  'sc_red_higher_equal_spade': 172.2,
  'sc_red_lower_inside_heart': 144.5,
  'sc_red_lower_inside_diamond': 133.6,
  'sc_red_lower_inside_club': 116.8,
  'sc_red_lower_inside_spade': 124.5,
  'sc_red_lower_outside_heart': 42.7,
  'sc_red_lower_outside_diamond': 42.7,
  'sc_red_lower_outside_club': 39.5,
  'sc_red_lower_outside_spade': 39.5,
  'sc_red_lower_equal_heart': 172.2,
  'sc_red_lower_equal_diamond': 172.2,
  'sc_red_lower_equal_club': 160.5,
  'sc_red_lower_equal_spade': 172.2,
  'sc_red_equal_outside_heart': 49.4,
  'sc_red_equal_outside_diamond': 49.4,
  'sc_red_equal_outside_club': 49.4,
  'sc_red_equal_outside_spade': 49.4,
  'sc_red_equal_equal_heart': 585.2,
  'sc_red_equal_equal_diamond': 585.2,
  'sc_red_equal_equal_club': 585.2,
  'sc_red_equal_equal_spade': 585.2,
  'sc_black_higher_inside_heart': 133.6,
  'sc_black_higher_inside_diamond': 124.5,
  'sc_black_higher_inside_club': 133.6,
  'sc_black_higher_inside_spade': 144.5,
  'sc_black_higher_outside_heart': 39.5,
  'sc_black_higher_outside_diamond': 39.5,
  'sc_black_higher_outside_club': 42.7,
  'sc_black_higher_outside_spade': 42.7,
  'sc_black_higher_equal_heart': 172.2,
  'sc_black_higher_equal_diamond': 160.5,
  'sc_black_higher_equal_club': 172.2,
  'sc_black_higher_equal_spade': 172.2,
  'sc_black_lower_inside_heart': 124.5,
  'sc_black_lower_inside_diamond': 124.5,
  'sc_black_lower_inside_club': 124.5,
  'sc_black_lower_inside_spade': 144.5,
  'sc_black_lower_outside_heart': 39.5,
  'sc_black_lower_outside_diamond': 39.5,
  'sc_black_lower_outside_club': 42.7,
  'sc_black_lower_outside_spade': 42.7,
  'sc_black_lower_equal_heart': 172.2,
  'sc_black_lower_equal_diamond': 172.2,
  'sc_black_lower_equal_club': 172.2,
  'sc_black_lower_equal_spade': 172.2,
  'sc_black_equal_outside_heart': 49.4,
  'sc_black_equal_outside_diamond': 49.4,
  'sc_black_equal_outside_club': 49.4,
  'sc_black_equal_outside_spade': 49.4,
  'sc_black_equal_equal_heart': 585.2,
  'sc_black_equal_equal_diamond': 585.2,
  'sc_black_equal_equal_club': 585.2,
  'sc_black_equal_equal_spade': 585.2,
  'hs_red_higher_inside_heart': 402.2,
  'hs_red_higher_inside_diamond': 370.5,
  'hs_red_higher_inside_club': 370.5,
  'hs_red_higher_inside_spade': 370.5,
  'hs_red_higher_outside_heart': 85.8,
  'hs_red_higher_outside_diamond': 93.9,
  'hs_red_higher_outside_club': 85.8,
  'hs_red_higher_outside_spade': 85.8,
  'hs_red_higher_equal_heart': 531.3,
  'hs_red_higher_equal_diamond': 531.3,
  'hs_red_higher_equal_club': 489.4,
  'hs_red_higher_equal_spade': 531.3,
  'hs_red_lower_inside_heart': 440.3,
  'hs_red_lower_inside_diamond': 402.2,
  'hs_red_lower_inside_club': 343.6,
  'hs_red_lower_inside_spade': 370.5,
  'hs_red_lower_outside_heart': 93.9,
  'hs_red_lower_outside_diamond': 93.9,
  'hs_red_lower_outside_club': 85.8,
  'hs_red_lower_outside_spade': 85.8,
  'hs_red_lower_equal_heart': 531.3,
  'hs_red_lower_equal_diamond': 531.3,
  'hs_red_lower_equal_club': 489.4,
  'hs_red_lower_equal_spade': 531.3,
  'hs_red_equal_outside_heart': 106.1,
  'hs_red_equal_outside_diamond': 106.1,
  'hs_red_equal_outside_club': 106.1,
  'hs_red_equal_outside_spade': 106.1,
  'hs_red_equal_equal_heart': 1910.2,
  'hs_red_equal_equal_diamond': 1910.2,
  'hs_red_equal_equal_club': 1910.2,
  'hs_red_equal_equal_spade': 1910.2,
  'hs_black_higher_inside_heart': 402.2,
  'hs_black_higher_inside_diamond': 370.5,
  'hs_black_higher_inside_club': 402.2,
  'hs_black_higher_inside_spade': 440.3,
  'hs_black_higher_outside_heart': 85.8,
  'hs_black_higher_outside_diamond': 85.8,
  'hs_black_higher_outside_club': 93.9,
  'hs_black_higher_outside_spade': 93.9,
  'hs_black_higher_equal_heart': 531.3,
  'hs_black_higher_equal_diamond': 489.4,
  'hs_black_higher_equal_club': 531.3,
  'hs_black_higher_equal_spade': 531.3,
  'hs_black_lower_inside_heart': 370.5,
  'hs_black_lower_inside_diamond': 370.5,
  'hs_black_lower_inside_club': 370.5,
  'hs_black_lower_inside_spade': 440.3,
  'hs_black_lower_outside_heart': 85.8,
  'hs_black_lower_outside_diamond': 85.8,
  'hs_black_lower_outside_club': 93.9,
  'hs_black_lower_outside_spade': 93.9,
  'hs_black_lower_equal_heart': 531.3,
  'hs_black_lower_equal_diamond': 531.3,
  'hs_black_lower_equal_club': 531.3,
  'hs_black_lower_equal_spade': 531.3,
  'hs_black_equal_outside_heart': 106.1,
  'hs_black_equal_outside_diamond': 106.1,
  'hs_black_equal_outside_club': 106.1,
  'hs_black_equal_outside_spade': 106.1,
  'hs_black_equal_equal_heart': 1910.2,
  'hs_black_equal_equal_diamond': 1910.2,
  'hs_black_equal_equal_club': 1910.2,
  'hs_black_equal_equal_spade': 1910.2,
});
