/**
 * Regenerate REPLAY_EVENTS.md from the published math.
 *
 *   node scripts/replay-events.js
 *
 * Stake's frontend approval asks for replay event IDs per bet mode covering
 * normal win, big win, win cap and loss. With 64 bet modes that is 256 IDs, so
 * they are derived from the published lookup tables rather than collected by
 * hand.
 *
 * Run this after every math rebuild: the simulation set changes, and so do the
 * IDs. The table is only meaningful against the build currently in
 * math-sdk/games/ride_the_bus/library/publish_files/.
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const PUBLISH = path.join(ROOT, 'math-sdk/games/ride_the_bus/library/publish_files');
const OUT = path.join(ROOT, 'REPLAY_EVENTS.md');

if (!fs.existsSync(path.join(PUBLISH, 'index.json'))) {
  console.error('No published math found at', PUBLISH);
  console.error('Run the math build first: cd math-sdk && .venv\\Scripts\\python.exe games\\ride_the_bus\\run.py');
  process.exit(1);
}

const idx = JSON.parse(fs.readFileSync(path.join(PUBLISH, 'index.json'), 'utf8'));

const rows = [];
for (const mode of idx.modes) {
  const txt = fs.readFileSync(path.join(PUBLISH, mode.weights), 'utf8');

  // Keep only rows the RGS can actually draw. A zero-weight row exists in the
  // table but can never be selected, so handing one to a reviewer as a replay
  // would be handing them a round that cannot happen.
  const drawable = [];
  const weightByPayout = new Map();
  for (const line of txt.split(/\r?\n/)) {
    if (!line) continue;
    const [id, w, p] = line.split(',');
    const weight = BigInt(w);
    if (weight === 0n) continue;
    const payout = Number(p);
    drawable.push({ id: Number(id), payout });
    weightByPayout.set(payout, (weightByPayout.get(payout) || 0n) + weight);
  }

  const losses = drawable.filter((r) => r.payout === 0);
  const wins = drawable.filter((r) => r.payout > 0).sort((a, b) => a.payout - b.payout);
  if (!wins.length) continue;

  const capPayout = wins[wins.length - 1].payout;

  // NORMAL WIN: the most likely payout that is an actual PROFIT, above 1.00x.
  // The most likely non-zero payout in every mode is 0.50x - the stage-2
  // consolation - which is a loss from the player's side and a strange thing to
  // hand a reviewer as the normal win.
  let normalPayout = null;
  let best = -1n;
  for (const [payout, weight] of weightByPayout) {
    if (payout <= 100) continue; // raw units: 100 = 1.00x
    if (weight > best) {
      best = weight;
      normalPayout = payout;
    }
  }
  if (normalPayout === null) normalPayout = wins[0].payout;

  // BIG WIN: the smallest payout worth at least a quarter of this mode's cap.
  // "Largest below the cap" put big win within a few percent of the cap in most
  // modes, so the two rounds demonstrated the same thing.
  const bigTarget = capPayout * 0.25;
  const bigCandidates = wins.filter((r) => r.payout >= bigTarget && r.payout < capPayout);
  const bigPayout = bigCandidates.length ? bigCandidates[0].payout : capPayout;

  const pick = (payout) => wins.find((r) => r.payout === payout) || null;

  rows.push({
    mode: mode.name,
    loss: losses[0] ? losses[0].id : null,
    normal: pick(normalPayout),
    big: pick(bigPayout),
    cap: pick(capPayout),
  });
}

const x = (r) => (r ? (r.payout / 100).toFixed(2) + 'x' : '-');
const id = (r) => (r ? String(r.id) : '-');
const caps = rows.map((r) => (r.cap ? r.cap.payout : 0));

let md = `# Replay event IDs

Stake's frontend approval requires replay event IDs to be supplied **per bet
mode**, covering normal win, big win, win cap and loss. This game has 64 bet
modes - one per full four-stage guess combination - so the table below lists all
256.

Generated by \`scripts/replay-events.js\`. **Regenerate after every math
rebuild**; the IDs are tied to the simulation set that produced them.

## What these IDs are, and the one thing to check first

These are **simulation IDs from the published lookup tables** in
\`math-sdk/games/ride_the_bus/library/publish_files/\`. Each row of a
\`lookUpTable_<mode>_0.csv\` is \`simulation number, weight, payout multiplier\`,
and every ID below has a non-zero weight, so each one is an outcome the RGS can
actually draw.

They are derived from the build, not observed from real play. The replay
endpoint is:

\`\`\`
GET {rgs_url}/bet/replay/{game}/{version}/{mode}/{event}
\`\`\`

**Confirm that \`{event}\` accepts a simulation ID before sending this table to
reviewers.** If they expect a round or bet ID issued by the RGS during live
play, these will need recapturing from a real session - but the scenarios and
payouts below still say exactly which round to go and play in each mode.

## How each scenario was chosen

| Scenario | Chosen as |
|---|---|
| Loss | The first drawable simulation paying 0x. |
| Normal win | The most likely payout that is an actual **profit** (above 1.00x). The most likely non-zero payout in every mode is 0.50x, the stage-2 consolation, which is a loss from the player's side. |
| Big win | The smallest payout worth at least **a quarter of that mode's cap**, so it is clearly large but still a different round from the cap. |
| Win cap | The highest payout the mode can produce. |

## The table

Payout multipliers are shown beside each ID so a reviewer can see what the round
is meant to demonstrate.

| Bet mode | Loss | Normal win | Big win | Win cap |
|---|---|---|---|---|
`;

for (const r of rows) {
  md += `| \`${r.mode}\` | ${r.loss ?? '-'} | ${id(r.normal)} (${x(r.normal)}) | ${id(r.big)} (${x(r.big)}) | ${id(r.cap)} (${x(r.cap)}) |\n`;
}

md += `
## Notes

- **${rows.length}** bet modes, **${rows.length * 4}** event IDs, all four distinct within every mode.
- The highest cap across all modes is **${(Math.max(...caps) / 100).toFixed(2)}x** - the game's overall maximum win, matching the figure stated in How to Play.
- The lowest per-mode cap is **${(Math.min(...caps) / 100).toFixed(2)}x**. Caps differ by mode because the ceiling depends on how unlikely the four guesses were.
- Every mode has a drawable loss, so no mode is missing a scenario.
`;

fs.writeFileSync(OUT, md);
console.log('wrote', path.relative(ROOT, OUT));
console.log(rows.length, 'modes,', rows.length * 4, 'event IDs');
console.log(
  'cap range',
  (Math.min(...caps) / 100).toFixed(2) + 'x',
  '-',
  (Math.max(...caps) / 100).toFixed(2) + 'x',
);
